# Generated by Django 4.0.4 on 2022-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_musicpack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpack',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
