# Generated by Django 4.0.4 on 2022-05-16 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_musicpack_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermusiclike',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='usermusiclist',
            name='artist',
        ),
        migrations.AddField(
            model_name='usermusiclike',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='music.musicpack'),
        ),
        migrations.AddField(
            model_name='usermusiclist',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='streamed', to='music.musicpack'),
        ),
    ]
