# Generated by Django 4.0.4 on 2022-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='role',
            field=models.CharField(default='user', max_length=15),
        ),
    ]
