# Generated by Django 4.0.4 on 2022-05-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bio_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='user',
            new_name='email',
        ),
    ]
