# Generated by Django 4.0.4 on 2022-05-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_bio_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='bio',
            new_name='shortbio',
        ),
    ]
