# Generated by Django 4.0.4 on 2022-05-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
