# Generated by Django 4.0.4 on 2022-05-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
