# Generated by Django 4.0.4 on 2022-05-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='total_likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='total_saved',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='total_viewed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
